### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by rgg-james** [soypat/decimate#1]
I'm trying to build the latest commit using the provided makefile.

However, I'm getting this error:

```
go build -ldflags="-s -w" -i -o bin/decimate.exe
main.go:18:8: cannot find package "github.com/soypat/decimate/cmd" in any of:
	/usr/lib/go/src/github.com/soypat/decimate/cmd (from $GOROOT)
	/home/james/go/src/github.com/soypat/decimate/cmd (from $GOPATH)
make: *** [Makefile:4: distr] Error 1
```

Unfortunately, I know nothing about the go build chain so wouldn't even know where to start with this.

**Comment by soypat** [comment]
Hey James. The way I see it you have two options:
1. Download Go from golang.org and try building it yourself
2. Download the [latest release](https://github.com/soypat/decimate/releases/tag/v1.0.1)

I believe the latest release does have some bugs so I'd recommend building latest source.

Cheers! And dont forget to run `decimate --help`

**Comment by soypat** [comment]
Option 3: I'll be updating the requirements and release as soon as I'm back at a PC
